AWSTemplateFormatVersion: '2010-09-09'
Description: TaskInfra Production - Create EKS Cluster (Control Plane Only)

Parameters:
  VpcId:
    Type: String
    Description: VPC ID for the EKS cluster

  SubnetIds:
    Type: CommaDelimitedList
    Description: Two subnet IDs (comma-separated)

  ClusterName:
    Type: String
    Default: TaskInfra-Prod-EKS-Cluster
    Description: Name for the EKS Cluster

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TaskInfra-Prod-EKS-ClusterRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - Key: Name
          Value: TaskInfra-Prod-EKS-ClusterRole

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: "1.29"
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds
        EndpointPublicAccess: true
        EndpointPrivateAccess: false
      AccessConfig:
        AuthenticationMode: "API_AND_CONFIG_MAP"
      Tags:
        - Key: Name
          Value: TaskInfra-Prod-EKS-Cluster

Outputs:
  ClusterName:
    Value: !Ref EKSCluster
    Export:
      Name: TaskInfra-Prod-EKS-ClusterName

  ClusterArn:
    Value: !GetAtt EKSCluster.Arn
    Export:
      Name: TaskInfra-Prod-EKS-ClusterArn

  ClusterRole:
    Value: !Ref EKSClusterRole
    Export:
      Name: TaskInfra-Prod-EKS-ClusterRole
